// Generated by scripts/fetch-events.mjs. Do not edit by hand.
// Refresh with: npm run fetch:events
import type { MedDevEvent } from "./events";

export const generatedUpcomingEvents: MedDevEvent[] = [];

export const generatedPastEvents: MedDevEvent[] = [
  {
    "id": "evt-88di2aV32pL3391",
    "name": "HealthTech Founders Match: Building the Next Generation of Healthcare",
    "url": "https://luma.com/1otzm5ud",
    "startAt": "2026-09-07T16:30:00.000Z",
    "dateLabel": "7 Sept 2026",
    "coverUrl": "https://images.lumacdn.com/uploads/uf/ad33cabf-7cfb-4337-99a8-a4429695de20.png",
    "location": "Sandstraße 33"
  },
  {
    "id": "evt-d7H13TEBYqrUFxx",
    "name": "2nd med-dev research conference (MDRC)",
    "url": "https://luma.com/dhh4mdwy",
    "startAt": "2026-07-01T15:30:00.000Z",
    "dateLabel": "1 Jul 2026",
    "coverUrl": "https://images.lumacdn.com/uploads/nl/480bc287-4f12-45ed-afd9-1ff54f19f6df.png",
    "location": "Google Kontorhaus"
  },
  {
    "id": "evt-HPdoo5GT2y2zfwc",
    "name": "med-dev x MLabAC: AI in Health Summit @ Netlight",
    "url": "https://luma.com/m36by6ds",
    "startAt": "2026-04-23T16:00:00.000Z",
    "dateLabel": "23 Apr 2026",
    "coverUrl": "https://images.lumacdn.com/event-covers/l9/f1c87d49-dc3b-4f45-877a-400f3e6bb76d.png",
    "location": "Netlight Consulting GmbH"
  },
  {
    "id": "evt-bVnS6EhlxZsufgM",
    "name": "med-dev x Wellster Digital Health Hackathon",
    "url": "https://luma.com/ugng7i30",
    "startAt": "2026-03-28T09:00:00.000Z",
    "dateLabel": "28 Mar 2026",
    "coverUrl": "https://images.lumacdn.com/event-covers/e6/f1194e2d-a4d8-4304-a93b-f8ce9b7db054.png",
    "location": "Wellster Healthtech Group"
  },
  {
    "id": "evt-QtJwFGUAFOtPChR",
    "name": "🧠 Med-Dev meets Brainlab",
    "url": "https://luma.com/w8tb2753",
    "startAt": "2026-01-28T14:30:00.000Z",
    "dateLabel": "28 Jan 2026",
    "coverUrl": "https://images.lumacdn.com/event-covers/4k/91122019-3c9e-44bd-bdd7-76f4eaf5712e.png",
    "location": "The Brainlab Tower"
  },
  {
    "id": "evt-TH18Ymfcof5sXZ0",
    "name": "Reverse Pitch Night",
    "url": "https://luma.com/kq09j4x8",
    "startAt": "2025-12-02T18:00:00.000Z",
    "dateLabel": "2 Dec 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/n3/55cdbab9-1928-46cd-8796-da976a5b114d.png",
    "location": "Neherstraße 1"
  },
  {
    "id": "evt-GUZO0FljVx5qAke",
    "name": "🌟 What I Do in My Day : A Day in the Life of Medicine & Tech Innovators 🌟",
    "url": "https://luma.com/icmoy33k",
    "startAt": "2025-11-24T16:30:00.000Z",
    "dateLabel": "24 Nov 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/uo/3ac623ac-131d-496b-9a25-cfbca19d469c.png",
    "location": "Nußbaumstraße 7"
  },
  {
    "id": "evt-weSFy3I4QhGVR2Q",
    "name": "From Lab to Launch: Driving Female Innovation",
    "url": "https://luma.com/wbfluena",
    "startAt": "2025-10-20T15:30:00.000Z",
    "dateLabel": "20 Oct 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/bk/b71b4344-ac50-42b5-80d8-97f73514ef59.png",
    "location": "Google Munich - Safety Engineering Center"
  },
  {
    "id": "evt-r2vcgy5agk7E89a",
    "name": "Expert Insight Session: Inside the World of Startup Exits in Healthcare",
    "url": "https://luma.com/ld4nlq6d",
    "startAt": "2025-09-17T16:00:00.000Z",
    "dateLabel": "17 Sept 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/kk/a54e65d8-6881-49e1-a096-a444d475263f.jpg",
    "location": "OMMAX"
  },
  {
    "id": "evt-L0GxDJt7zDFG0ej",
    "name": "med-dev.org x MIT Hacking Medicine: Health Tech Connect Boston",
    "url": "https://luma.com/9avv5xv7",
    "startAt": "2025-09-03T22:00:00.000Z",
    "dateLabel": "3 Sept 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/jb/242273f8-f884-49aa-80c2-f0c38a973bba.png",
    "location": "139 Main St"
  },
  {
    "id": "evt-j2qeexL6Xsp5upG",
    "name": "med-dev meets Life Science Factory",
    "url": "https://luma.com/ev4mhm5l",
    "startAt": "2025-07-08T17:00:00.000Z",
    "dateLabel": "8 Jul 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/wg/bfc7be5e-5685-4186-80a5-2294ed80140e.jpg",
    "location": "Ingolstädter Landstraße 1"
  },
  {
    "id": "evt-LGdJ5HlOxPPn6DN",
    "name": "🧠Med-Dev meets Brainlab",
    "url": "https://luma.com/bj5nse8i",
    "startAt": "2025-06-26T13:30:00.000Z",
    "dateLabel": "26 Jun 2025",
    "coverUrl": "https://images.lumacdn.com/event-covers/xr/896dab37-c97a-4c86-b057-4f8a99c4dcdb.png",
    "location": "The Brainlab Tower"
  }
];
