// Pulls the med-dev event list off the public Luma calendar and writes it into
// the source tree, so the site can render events without any client-side call.
//
// Why build time: api.lu.ma answers unauthenticated, but sends no
// Access-Control-Allow-Origin, so a browser fetch is blocked. Luma's own embed
// is no substitute either - it only ever renders *upcoming* events, and the
// calendar is often empty.
//
// The generated file is committed, so a clean clone builds with no network.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const siteLinksPath = join(root, "src", "content", "siteLinks.ts");
const outPath = join(root, "src", "content", "events.generated.ts");

const perPeriod = 12;

/** The embed URL in siteLinks.ts stays the single source of truth for the id. */
async function readCalendarId() {
  const source = await readFile(siteLinksPath, "utf8");
  const id = source.match(/\/calendar\/(cal-[A-Za-z0-9]+)/)?.[1];

  if (!id) {
    throw new Error(`No cal- id found in ${siteLinksPath}`);
  }

  return id;
}

async function fetchPeriod(calendarId, period) {
  const url =
    `https://api.lu.ma/calendar/get-items?calendar_api_id=${encodeURIComponent(calendarId)}` +
    `&period=${period}&pagination_limit=${perPeriod}`;

  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Luma responded ${response.status} for period=${period}`);
  }

  const payload = await response.json();

  return (payload.entries ?? []).map(toEvent).filter(Boolean);
}

function toEvent(entry) {
  const event = entry?.event;

  if (!event?.api_id || !event.name || !event.url || !event.start_at) {
    return null;
  }

  const geo = event.geo_address_info;
  // "mode" is Luma's own switch for whether the venue may be shown at all.
  // "address" is the venue line Luma itself displays; "description" is a free
  // text note and is often arrival directions rather than a place name.
  const location = geo && geo.mode === "shown" ? geo.address || geo.city || undefined : undefined;

  return {
    id: event.api_id,
    name: event.name,
    url: `https://luma.com/${event.url}`,
    startAt: event.start_at,
    dateLabel: formatDate(event.start_at, event.timezone),
    coverUrl: event.cover_url ?? undefined,
    location,
  };
}

/**
 * Formatted here rather than in the component: toLocaleDateString depends on
 * the host's timezone, so formatting a prerendered date during render would be
 * a hydration mismatch for any event near midnight UTC.
 */
function formatDate(startAt, timezone) {
  return new Date(startAt).toLocaleDateString("en-GB", {
    dateStyle: "medium",
    timeZone: timezone || "Europe/Berlin",
  });
}

const calendarId = await readCalendarId();
const [upcoming, past] = await Promise.all([
  fetchPeriod(calendarId, "future"),
  fetchPeriod(calendarId, "past"),
]);

// Soonest first for upcoming, most recent first for past: both orders put the
// entry a visitor cares about most at the top of the list.
upcoming.sort((a, b) => a.startAt.localeCompare(b.startAt));
past.sort((a, b) => b.startAt.localeCompare(a.startAt));

const file = `// Generated by scripts/fetch-events.mjs. Do not edit by hand.
// Refresh with: npm run fetch:events
import type { MedDevEvent } from "./events";

export const generatedUpcomingEvents: MedDevEvent[] = ${JSON.stringify(upcoming, null, 2)};

export const generatedPastEvents: MedDevEvent[] = ${JSON.stringify(past, null, 2)};
`;

await writeFile(outPath, file, "utf8");

console.log(`Wrote ${upcoming.length} upcoming and ${past.length} past events to ${outPath}`);
